version: '3'

services:
  db:
    container_name: task_manager_db_test
    image: mysql:5.7
    env_file:
      - .env.mysql

  backend:
    container_name: task_manager_backend_test
    image: task_manager_backend
    build: ./backend
    volumes:
      - ./backend:/app
    links:
      - db
    ports:
      - "5000:80"
    env_file:
      - .env
      - .env.mysql
      - .env.secret
    environment:
      EMAIL: 'noreply@task_manager.com'
      MAIL_USERNAME: ''
      MAIL_PASSWORD: ''
      SMTP_SERVER:  "dockerhost"
      SMTP_PORT: 1025
    depends_on:
      - dockerhost

  mailhog:
    container_name: task_manager_mailhog_test
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    logging:
      driver: none 

  tests:
    container_name: task_manager_tests
    image: task_manager_tests
    build: ./backend_tests
    volumes:
      - ./backend_tests/tests:/home/tests
    env_file:
      - .env
    environment:
      BACKEND_URL: "http://dockerhost:5000"
      MAILHOG_URL: "http://dockerhost:8025"


  dockerhost:
    image: qoomon/docker-host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: on-failure
