version: '3'

services:
  db:
    container_name: task_manager_db_e2e
    image: mysql:5.7
    env_file:
      - .env.mysql

  backend:
    container_name: task_manager_backend_e2e
    image: task_manager_backend
    build: ./backend
    volumes:
      - ./backend:/app
    links:
      - db
    ports:
      - "5000:80"
    env_file:
      - .env
      - .env.mysql
      - .env.secret
    environment:
      EMAIL: 'noreply@task_manager.com'
      MAIL_USERNAME: ''
      MAIL_PASSWORD: ''
      SMTP_SERVER:  "dockerhost"
      SMTP_PORT: 1025
    depends_on:
      - dockerhost

  frontend:
    container_name: task_manager_frontend_e2e
    image: nginx:stable-alpine
    ports:
      - 80:80
    environment:
      API_URL: "http://dockerhost:5000"
    volumes:
      - ./frontend/nginx.tmpl:/etc/nginx/conf.d/nginx.tmpl
      - ./frontend/app/build:/usr/share/nginx/html
    command: /bin/sh -c "envsubst
     '$$API_URL' < /etc/nginx/conf.d/nginx.tmpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - dockerhost

  mailhog:
    container_name: task_manager_mailhog_e2e
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    logging:
      driver: none 

  e2e:
    container_name: task_manager_e2e_test
    image: task_manager_e2e
    build: ./e2e
    volumes:
      - ./e2e:/e2e
    working_dir: /e2e
    environment:
      CYPRESS_baseUrl: "http://dockerhost"
      BACKEND_URL: "http://dockerhost:5000"
      FRONTEND_URL: "http://dockerhost"
    depends_on:
      - dockerhost
    entrypoint:
      - /wait-for-services.sh
      - cypress
      - run
      - --env
      - "MAIL_SERVER_URL=http://dockerhost:8025/,USERNAME=${SUPERUSER_USERNAME},PASSWORD=${SUPERUSER_PASSWORD}"


  dockerhost:
    image: qoomon/docker-host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: on-failure
